### ISSUE TITLE
Investigate the tests failures

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/YODA-Tools#19]
Before I start changing the code we should try to get Travis-CI to work so I don't introduce bugs or breakages to the code.

See https://travis-ci.org/ODM2/YODA-Tools/builds/231737622

@sreeder do you have an idea of what is going on with Travis-CI? The last green build was https://travis-ci.org/ODM2/YODA-Tools/builds/206801750

**Comment by sreeder** [comment]
@ocefpaf  I am looking into this now and will let you know when I have more information.

**Comment by sreeder** [comment]
@ocefpaf this issue is being caused by trying to connect to a local sql database that obviously does not exist  on the testing server. Since you have a little more experience with TravisCI I was wondering what your suggestion was for testing when you need to be connected to a live database. The API loads a mysql database onto its local server for testing. Should we do that or try and set up a sqlite database to test against or is there a better option? Thanks for your help!

**Comment by ocefpaf** [comment]
> @ocefpaf this issue is being caused by trying to connect to a local sql database that obviously does not exist on the testing server.

Got it. The last [commit](https://github.com/ODM2/YODA-Tools/blob/f6000fd420d41bdeaf113961df75c0868d2ff43c/.travis.yml#L41-L43) before #21 had the database script commented out, so I though those were not needed.

> Since you have a little more experience with TravisCI I was wondering what your suggestion was for testing when you need to be connected to a live database.

I'll try to re-enable Travis-CI own versions of those services by restoring the lines:

```yaml
services:
  - mysql
  - postgresql
```

> The API loads a mysql database onto its local server for testing. Should we do that or try and set up a sqlite database to test against or is there a better option?

I guess that is the next step. I'll experiment a little bit with the services above and then I'll ping you for help with that. (I don't really know anything about databases to follow up after that.)

**Comment by ocefpaf** [comment]
Actually, now that I took a closer look at the logs, we had 2 tests in the last passing status and 6 [here](https://travis-ci.org/ODM2/YODA-Tools/builds/231737622#L580). It seems that #21 can run those same 6 without any database service. So I am closing this and, if we add more tests that requires databases, we can re-enable that.
