### ISSUE TITLE
xlrd not installed as dependency to conda package

### ISSUE THREAD

**Issue by emiliom** [ODM2/YODA-Tools#32]
I see that `xlrd` is on requirements.txt, but it doesn't get installed as a dependency when the yotdatools conda package is installed. Hmm.

@ocefpaf, any idea what's going on?

**Comment by ocefpaf** [comment]
That was an oversight on my part. See https://github.com/ODM2/conda-recipes-ODM2/pull/68

**Comment by emiliom** [comment]
Thanks!
